import java.util.Scanner;

public class exception {
    public static void main(String[] args) {
        // int num=6;
        // int num1=0;
        // int result=0;
        // int values[]={4,5,6,7};
        String name=null;
        Scanner sc=new Scanner(System.in);
        name=sc.next();
        sc.close();
        // try {
        //     result=num/num1;
        //     System.out.println(values[9]);
        //    // System.out.println("in try block");
        // }
        // catch(Exception e)
        // {
        //     System.out.println("in catch block"+e);
        // }
        System.out.println(name);
        // System.out.println("bye");
    }
}
